name: Deploy FastAPI Book Project
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python Env
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/blessing-azure.pem
        chmod 600 ~/.ssh/blessing-azure.pem
    - name: Deploy to Azure
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/blessing-azure.pem blessing@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/blessing/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi